width = Window.GetWidth();
height = Window.GetHeight();
logo;
# scp_foundation;
time = 0.0;


fun clamp_01(t) {
	if (t > 1)
		return 1;
	else if (t < 0)
		return 0;
	return t;
}


fun out_quadratic(t) {
	t = clamp_01(t);
	val = (1 - t);
	return (1 - (val * val * val));
}


fun refresh_callback ()
{
	time++;
	opacity = out_quadratic((time - 20) / 40);
	logo.sprite.SetOpacity(opacity);
}
Plymouth.SetRefreshFunction (refresh_callback);


fun init() {
    Window.SetBackgroundTopColor(0, 0, 0);
    Window.SetBackgroundBottomColor(0, 0, 0);

    logo.image = Image("logo.png");
    logo.image = logo.image.Scale(logo.image.GetWidth() * 0.25, logo.image.GetHeight() * 0.25);
    logo.sprite = Sprite(logo.image);
    logo.x = ((width / 2) - (logo.image.GetWidth() / 2));
    logo.y = ((height / 2) - (logo.image.GetHeight() / 2));
    logo.sprite.SetPosition(logo.x, logo.y, 1000);
    logo.sprite.SetOpacity(0);

    # scp_foundation.text = Image.Text("SCP Foundation", 1, 1, 1, 0.8, "center");
    # scp_foundation.sprite = Sprite(scp_foundation.text);
    # scp_foundation.sprite.SetImage(scp_foundation.text);
    # scp_foundation.x = ((width / 2) - (scp_foundation.text.GetWidth() / 2));
    # scp_foundation.y = 200;
    # scp_foundation.sprite.SetPosition(scp_foundation.x, scp_foundation.y, 1005);
    # scp_foundation.sprite.SetOpacity(1);

    if (Plymouth.GetMode() != "boot") {
    }
}


init();
