width = Window.GetWidth();
height = Window.GetHeight();
logo_offset = 100;
logo;
spacing = 20;
scp_foundation;
total_width;
secure;
contain;
protect;
time = 0.0;


fun clamp_01(t) {
	if (t > 1)
		return 1;
	else if (t < 0)
		return 0;
	return t;
}


fun out_cubic(t) {
	t = clamp_01(t);
	val = (1 - t);
	return (1 - (val * val * val));
}


fun refresh_callback ()
{
	time++;
	opacity = out_cubic((time - 20) / 20);
	logo.sprite.SetOpacity(opacity);

	opacity = out_cubic((time - 35) / 15);
	scp_foundation.sprite.SetOpacity(opacity);

	target_opacity = 0.7;
	offset_max = 10;

	t = ((time - 70) / 15);
	offset = ((1 - out_cubic(t)) * offset_max);
	secure.x = ((width - total_width) / 2  + offset);
	secure.sprite.SetPosition(secure.x, secure.y, 1000);
	opacity = (out_cubic(t) * target_opacity);
	secure.sprite.SetOpacity(opacity);

	t = ((time - 85) / 15);
	offset = ((1 - out_cubic(t)) * offset_max);
	contain.x = (secure.x + secure.image.GetWidth() + spacing + offset);
	contain.sprite.SetPosition(contain.x, contain.y, 1000);
	opacity = (out_cubic(t) * target_opacity);
	contain.sprite.SetOpacity(opacity);

	t = ((time - 100) / 15);
	offset = ((1 - out_cubic(t)) * offset_max);
	protect.x = (contain.x + contain.image.GetWidth() + spacing + offset);
	protect.sprite.SetPosition(protect.x, protect.y, 1000);
	opacity = (out_cubic(t) * target_opacity);
	protect.sprite.SetOpacity(opacity);
}
Plymouth.SetRefreshFunction (refresh_callback);


fun init() {
    Window.SetBackgroundTopColor(0, 0, 0);
    Window.SetBackgroundBottomColor(0, 0, 0);

    logo.image = Image("logo.png");
    logo.image = logo.image.Scale(logo.image.GetWidth() * 0.25, logo.image.GetHeight() * 0.25);
    logo.sprite = Sprite(logo.image);
    logo.x = ((width / 2) - (logo.image.GetWidth() / 2));
    logo.y = ((height / 2) - (logo.image.GetHeight() / 2) - logo_offset);
    logo.sprite.SetPosition(logo.x, logo.y, 1000);
    logo.sprite.SetOpacity(0);


	scp_foundation.image = Image("scp_foundation.png");
    scp_foundation.image = scp_foundation.image.Scale(scp_foundation.image.GetWidth() * 0.5, scp_foundation.image.GetHeight() * 0.5);
	scp_foundation.sprite = Sprite(scp_foundation.image);
	scp_foundation.x = ((width / 2) - (scp_foundation.image.GetWidth() / 2));
	scp_foundation.y = (logo.y + logo.image.GetHeight() + spacing);
	scp_foundation.sprite.SetPosition(scp_foundation.x, scp_foundation.y, 1000);
	scp_foundation.sprite.SetOpacity(0);


	y = (scp_foundation.y + scp_foundation.image.GetHeight());
	secure.image = Image("secure.png");
	secure.image = secure.image.Scale(secure.image.GetWidth() * 0.5, secure.image.GetHeight() * 0.5);
	secure.sprite = Sprite(secure.image);
	secure.y = y;

	contain.image = Image("contain.png");
	contain.image = contain.image.Scale(contain.image.GetWidth() * 0.5, contain.image.GetHeight() * 0.5);
	contain.sprite = Sprite(contain.image);
	contain.y = y;

	protect.image = Image("protect.png");
	protect.image = protect.image.Scale(protect.image.GetWidth() * 0.5, protect.image.GetHeight() * 0.5);
	protect.sprite = Sprite(protect.image);
	protect.y = y;

	total_width = (secure.image.GetWidth() + contain.image.GetWidth() + protect.image.GetWidth() + (2 * spacing));
	secure.x = ((width - total_width) / 2);
	contain.x = (secure.x + secure.image.GetWidth() + spacing);
	protect.x = (contain.x + contain.image.GetWidth() + spacing);

	secure.sprite.SetPosition(secure.x, secure.y, 1000);
	secure.sprite.SetOpacity(0);
	contain.sprite.SetPosition(contain.x, contain.y, 1000);
	contain.sprite.SetOpacity(0);
	protect.sprite.SetPosition(protect.x, protect.y, 1000);
	protect.sprite.SetOpacity(0);


    if (Plymouth.GetMode() != "boot") {
	    logo.sprite.SetOpacity(1);
		scp_foundation.sprite.SetOpacity(1);
		secure.sprite.SetOpacity(1);
		contain.sprite.SetOpacity(1);
		protect.sprite.SetOpacity(1);
    }
}


init();
